  name: calcium
  channels:
    - defaults
    - conda-forge
  dependencies:
    - python=3.9
    - numpy
    - pandas
    - matplotlib
    - seaborn
    - pip
    - pip:
      - cupy-cuda12x
      - peakutils
      - py7zr